[package]
name = "sbd-gen"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ariel-os/sbd"

[dependencies]
anyhow = "1.0.99"
argh = "0.1.13"
camino = "1.1.11"
indexmap = { version = "2.11.0", features = ["serde"] }
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_with = "3.14.0"
serde_yaml = "0.9.34"
toml = { version = "0.9.5", features = ["preserve_order"] }
walkdir = "2.5.0"
yaml-hash = "0.4.5"

[lints.clippy]
pedantic = "deny"
